FROM python:3.7-slim

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV NUM_PROCS=4
ENV BOKEH_RESOURCES=cdn

RUN apt-get update \
    && apt-get install gcc -y \
    && apt-get clean

WORKDIR /demo.bokeh.org

COPY . .
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt
RUN python -c 'import bokeh; bokeh.sampledata.download(progress=False)'
RUN cd ./examples/app/stocks && python download_sample_data.py && cd /

EXPOSE 8080

CMD bokeh serve \
    --allow-websocket-origin="*" \
    --index=/demo.bokeh.org/index.html \
    --num-procs=${NUM_PROCS} \
    ./examples/app/clustering \
    ./examples/app/crossfilter \
    ./examples/app/dash \
    ./examples/app/export_csv \
    ./examples/app/fourier_animated.py \
    ./examples/app/gapminder \
    ./examples/app/image_blur.py \
    ./examples/app/movies \
    ./examples/app/ohlc \
    ./examples/app/population.py \
    ./examples/app/selection_histogram.py \
    ./examples/app/sliders.py \
    ./examples/app/spectrogram \
    ./examples/app/surface3d \
    ./examples/app/stocks \
    ./examples/app/taylor.py \
    ./examples/app/weather